# Generated by Django 6.0.2 on 2026-03-11 08:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("story", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="story",
            name="title",
            field=models.CharField(max_length=512),
        ),
        migrations.AlterField(
            model_name="story",
            name="url",
            field=models.URLField(
                max_length=1000,
                validators=[django.core.validators.URLValidator()],
            ),
        ),
    ]
