# Generated by Django 6.0.2 on 2026-03-13 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("story", "0002_alter_story_title_alter_story_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="story",
            name="url",
            field=models.URLField(db_index=True, max_length=1000),
        ),
    ]
