# Generated by Django 6.0.2 on 2026-03-16 10:56

import django.contrib.postgres.indexes
import django.core.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("company", "0004_alter_company_name_alter_company_url_and_more"),
        ("source", "0003_remove_source_source_sour_name_ff2cbb_idx_and_more"),
        ("story", "0003_alter_story_url"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="story",
            name="story_story_title_dc26fd_idx",
        ),
        migrations.AlterField(
            model_name="story",
            name="url",
            field=models.TextField(
                validators=[django.core.validators.URLValidator()]
            ),
        ),
        migrations.AddIndex(
            model_name="story",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["title"],
                name="story_title_gin",
                opclasses=["gin_trgm_ops"],
            ),
        ),
    ]
