# Generated by Django 6.0.2 on 2026-03-16 22:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("company", "0004_alter_company_name_alter_company_url_and_more"),
        ("source", "0004_remove_source_source_name_gin_idx_and_more"),
        ("story", "0004_remove_story_story_story_title_dc26fd_idx_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="story",
            name="story_title_gin",
        ),
        migrations.AlterField(
            model_name="story",
            name="url",
            field=models.URLField(db_index=True, max_length=1000),
        ),
        migrations.AddIndex(
            model_name="story",
            index=models.Index(
                fields=["title"], name="story_story_title_dc26fd_idx"
            ),
        ),
    ]
