# Generated by Django 6.0.2 on 2026-03-13 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("company", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="company",
            name="name",
            field=models.CharField(db_index=True, max_length=256),
        ),
        migrations.AlterField(
            model_name="company",
            name="url",
            field=models.URLField(db_index=True),
        ),
    ]
