# Generated by Django 6.0.2 on 2026-03-17 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("company", "0004_alter_company_name_alter_company_url_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="company",
            name="name",
            field=models.CharField(max_length=256, unique=True),
        ),
    ]
