# Generated by Django 6.0.2 on 2026-03-17 04:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("company", "0005_alter_company_name"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="company",
            unique_together={("name", "url")},
        ),
    ]
