# Generated by Django 6.0.2 on 2026-03-17 07:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("company", "0006_alter_company_unique_together"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="company",
            unique_together=set(),
        ),
    ]
