# Generated by Django 6.0.2 on 2026-03-17 09:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("company", "0007_alter_company_unique_together"),
    ]

    operations = [
        migrations.AlterField(
            model_name="company",
            name="name",
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name="company",
            name="url",
            field=models.TextField(
                unique=True, validators=[django.core.validators.URLValidator()]
            ),
        ),
    ]
