# Generated by Django 6.0.2 on 2026-03-16 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("source", "0003_remove_source_source_sour_name_ff2cbb_idx_and_more"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="source",
            name="source_name_gin_idx",
        ),
        migrations.RemoveIndex(
            model_name="source",
            name="source_url_gin_idx",
        ),
        migrations.AlterField(
            model_name="source",
            name="name",
            field=models.CharField(db_index=True, max_length=256),
        ),
        migrations.AlterField(
            model_name="source",
            name="url",
            field=models.URLField(db_index=True),
        ),
    ]
