# Generated by Django 6.0.2 on 2026-03-16 22:54

import django.contrib.postgres.indexes
import django.core.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("company", "0004_alter_company_name_alter_company_url_and_more"),
        ("source", "0004_remove_source_source_name_gin_idx_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="source",
            name="name",
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name="source",
            name="url",
            field=models.TextField(
                validators=[django.core.validators.URLValidator()]
            ),
        ),
        migrations.AddIndex(
            model_name="source",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["name"],
                name="source_name_gin_idx",
                opclasses=["gin_trgm_ops"],
            ),
        ),
        migrations.AddIndex(
            model_name="source",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["url"],
                name="source_url_gin_idx",
                opclasses=["gin_trgm_ops"],
            ),
        ),
    ]
